import './globals.css';

import type { Metadata } from 'next';

import { InjectorAccentColor } from '@/components/InjectorAccentColor';

export const lang = 'en';

export const metadata: Metadata = {
  title: 'Itachi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={lang}>
      <body>
        {children}
        <InjectorAccentColor />
      </body>
    </html>
  );
}
