import "@/styles/global.css";

import type { Metadata } from "next";

import { ClientInjector } from "@/components/injector/client/Injector";
import { LayoutHeader } from "@/components/layout/header/Header";
import { ClientProvider } from "@/components/provider/client/Provider";

export const lang = "en";

export const metadata: Metadata = {
  title: "Itachi",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={lang}>
      <head>{/* <style>{getAccentColorStyleText()}</style> */}</head>
      <body>
        <LayoutHeader />
        {children}
        <ClientProvider />
        <ClientInjector />
      </body>
    </html>
  );
}
