import '@/styles/index.css';

import type { Metadata } from 'next';
import Script from 'next/script';
import type { PropsWithChildren } from 'react';

import { HydrationEndDetector } from '@/components/common/HydrationEndDetector';
import { Root } from '@/components/layout/root/Root';
import { AccentColorStyleInjector } from '@/components/modules/shared/AccentColorStyleInjector';
import { sansFont, serifFont } from '@/lib/fonts';
import PKG from '@/package.json';
import { WebAppProviders } from '@/providers/root';
import { AggregationProvider } from '@/providers/root/aggregation-data-provider';

const { version } = PKG;

export const metadata: Metadata = {
  title: 'Itachi',
  description: 'Generated by create next app'
};

export default async function RootLayout(props: PropsWithChildren) {
  const { children } = props;

  const data = {
    user: {
      id: '',
      introduce: '当第一颗卫星飞向大气层外，我们便以为自己终有一日会征服宇宙。',
      mail: 'shawliu996@gmail.com',
      name: 'Shawfix',
      username: 'Shawfix',
      avatar: 'https://avatars.githubusercontent.com/u/75828211?v=4',
      lastLoginAt: '',
      lastLoginIp: '',
      createdAt: '',
      creatorId: 'admin',
      creatorName: 'admin',
      modifiedAt: '',
      modifierId: 'admin',
      modifierName: 'admin'
    },
    seo: {
      title: '你能做我的猫吗的个人博客',
      description: 'Clean, Cute, Fast.',
      icon: '/favicon.ico',
      keywords: ['Gyoza', 'blog', 'Astro', 'theme', 'lxchapu', '博客主题']
    }
  };

  const config = {
    hero: {
      title: {
        template: [
          {
            type: 'h1',
            text: "Hi, I'm",
            class: 'font-light text-4xl leading-10'
          },
          {
            type: 'h1',
            text: 'Shawfix',
            class: 'font-medium mx-2 text-4xl leading-10'
          },
          {
            type: 'h1',
            text: '👋。',
            class: 'font-light text-4xl leading-10'
          },
          {
            type: 'br'
          },
          {
            type: 'h1',
            text: 'A ',
            class: 'font-light text-4xl leading-10'
          },
          {
            type: 'code',
            text: '</> Developer & #Musician',
            class:
              'font-medium mx-2 text-3xl rounded p-1 bg-gray-200 dark:bg-gray-800/0 hover:dark:bg-gray-800/100 bg-opacity-0 hover:bg-opacity-100 transition-background duration-200 leading-10'
          },
          {
            type: 'span',
            class:
              'inline-block w-[1px] h-8 -bottom-2 relative bg-gray-800/80 dark:bg-gray-200/80 opacity-0 group-hover:opacity-100 transition-opacity duration-200 group-hover:animation-blink leading-10'
          }
        ]
      },
      description: 'Working in Mog and Jwc.js for a magical web world.'
    },
    site: {
      favicon: '/favicon.ico'
    }
  };

  return (
    <html lang="zh-CN" className="noise themed" suppressHydrationWarning>
      <head>
        <AccentColorStyleInjector />
        <SayHi />
        <HydrationEndDetector />
      </head>
      <body
        className={`${sansFont.variable} ${serifFont.variable} m-0 h-full p-0 font-sans`}
      >
        <WebAppProviders>
          <AggregationProvider appConfig={config} aggregationData={data}>
            <div data-theme>
              <Root>{children}</Root>
            </div>
          </AggregationProvider>
        </WebAppProviders>
      </body>
    </html>
  );
}

const SayHi = () => {
  return (
    <Script>
      {`var version = "${version}";
        (${function () {
          console.log(
            `%c Mix Space %c https://github.com/mx-space`,
            'color: #fff; margin: 1em 0; padding: 5px 0; background: #2980b9;',
            'margin: 1em 0; padding: 5px 0; background: efefef;'
          );
          console.log(
            `%c Shiro ${window.version} %c https://innei.in`,
            'color: #fff; margin: 1em 0; padding: 5px 0; background: #39C5BB;',
            'margin: 1em 0; padding: 5px 0; background: #effef;'
          );

          const motto = `
    This Personal Space Powered By Mix Space.
    Written by TypeScript, Coding with Love.
    --------
    Stay hungry. Stay foolish. --Steve Jobs
    `;

          if (document.firstChild?.nodeType !== Node.COMMENT_NODE) {
            document.prepend(document.createComment(motto));
          }
        }.toString()})();`}
    </Script>
  );
};

declare global {
  interface Window {
    version: string;
  }
}
